### ISSUE TITLE
Clarify conflict with aw-watcher-afk

### ISSUE THREAD

**Issue by varac** [ActivityWatch/aw-watcher-window-wayland#23]
The [How to use](https://github.com/ActivityWatch/aw-watcher-window-wayland#how-to-use) instructions tell:

> Start aw-server (or aw-qt, but you need to disable aw-watcher-afk and aw-watcher-window so they don't conflict)

Why does this watcher conflict with aw-watcher-afk ? 
Does it also tracks afk times and reports them to the server ?

**Comment by johan-bjareholt** [comment]
> Does it also tracks afk times and reports them to the server?

Correct, that is stated in the first sentence in the README.

> Reports both window and afk status to the buckets aw-watcher-window and aw-watcher-afk respectively
